//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Record.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAARwOaZZFBwUyBvdMiF3L66QAAAAACAAAAAAAQZgAAAAEAACAAAABq/175SnJzN3Cy9KpQ+SMdDG3/61emO5JBkzyMkgt1TQAAAAAOgAAAAAIAACAAAADRWNZVYkbODKjFxsdcewoduWVz5HmQ7vqVoYkJKQSD/CAAAABG7skjTwwNscOTWtVpIqAPyj3kzZv3aWa8jTBTj/ywhUAAAADuWWzZ+WhdWH77K+qLQFAPujxmRAtBirZ48pMO3iU4E8wVC+xZzEgBsIl+NcNHTOpXiz5FqXd8BMG1pPQ7T3m0")]
        public string serverIP {
            get {
                return ((string)(this["serverIP"]));
            }
            set {
                this["serverIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RADMS")]
        public string databaseName {
            get {
                return ((string)(this["databaseName"]));
            }
            set {
                this["databaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAARwOaZZFBwUyBvdMiF3L66QAAAAACAAAAAAAQZgAAAAEAACAAAADM9QhzCcZnDJ/eESl2TWnuKhe1wl3os6diRxkdoiJgsgAAAAAOgAAAAAIAACAAAACJ2bNYTZtNnRThz0081R6lB5hiBCJ4LIC25hs4lWKBBxAAAADSsse15v+4ODu9lu+9Aq/0QAAAABicojwjJRD0amsF0l2t2k+PXUVHjP0Kjkncg5n6ij3sskdk553LzReQ45Qoogj8mMUt5gJeMu5fxl0YxPv5gd4=")]
        public string serverUID {
            get {
                return ((string)(this["serverUID"]));
            }
            set {
                this["serverUID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAARwOaZZFBwUyBvdMiF3L66QAAAAACAAAAAAAQZgAAAAEAACAAAACY+BebAlLyoKfuGFfMWN15oTS5GA6T0EjOocf3xOQwGgAAAAAOgAAAAAIAACAAAAAgZDfB9oMPoQsbybzrqj8CLC5SaBRin5xtSsWkUN5eQSAAAABARdCVRf6Asb6MoTF55U+wlQRKn+eae/TqCseM0KhUN0AAAAD6ZkR7Vxi2iM79cJdJby8NujlKzO9OvWx/haK/QeA1BOHUGS4TdKMD1l5Asjyweqa/m4N3V0kXlxALtd7I7Xt6")]
        public string ServerPSW {
            get {
                return ((string)(this["ServerPSW"]));
            }
            set {
                this["ServerPSW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string userauth {
            get {
                return ((string)(this["userauth"]));
            }
            set {
                this["userauth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string userauthpass {
            get {
                return ((string)(this["userauthpass"]));
            }
            set {
                this["userauthpass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string userid {
            get {
                return ((string)(this["userid"]));
            }
            set {
                this["userid"] = value;
            }
        }
    }
}
